vars: {
  d2-config: {
    theme-id: 300
  }
}

endpoint: {
  near: top-left
}

new endpoint: {
  near: top-right
}
error page: {
  near: bottom-right
}

api: temp session storage
api: {
  # direction: right
  near: bottom-center
  shape: sequence_diagram

  request
  session
  rdb
  response-ok
  response-fail

  session: redis\n(sessioninfo)
  session: {
    shape: cylinder
  }

  rdb: oracle\n(userinfo)
  rdb: {
    shape: cylinder
  }
}

endpoint -> api.request: |md
  * post(/login) with parameter (new endpoint)
  * post(/authed) with parameter (new endpoint)
|

api.session check: {
  request -> session
}
api.session update: {
  request <- session: exists session
  request -> response-ok: success
}
api.get userinfo: {
  request <- session: not exists session
  request -> rdb: get userinfo
}
api.exists user: {
    request <- rdb: exists user
    request -> response-ok: success
  }
  api.not exists user: {
  request <- rdb: not exists user
  request -> response-fail: move error page
}

api.response-ok -> new endpoint
api.response-fail -> error page
